### ISSUE TITLE
Merge Plugin Features: TemplateTitle

### ISSUE THREAD

**Issue by aljawaid** [aljawaid/TemplateManager#10]
- [x] Merge JS code
- [x] Keep compatibility with TemplateTitle (https://github.com/creecros/TemplateTitle/commit/3877f91ac4f2e802bfc24bbfe2b6305e06c4f31d)
- [x] #11
- [x] Update README
- [x] Update plugin description

**Comment by aljawaid** [comment]
@creecros Just one issue it seems, I'm trying to avoid the overrides and add it into a hook but...

in the `template:task:form:first-column` hook (task creation):
```php
<?= $this->helper->templateTitleHelper->renderDescriptionAndTitleTemplateDropdown($project['id']) ?>
```
but I get:
```
PHP Notice:  Trying to access array offset on value of type null
```

in the `template:task:form:first-column` hook (task modification):
```php
<?= $this->helper->templateTitleHelper->renderDescriptionAndTitleTemplateDropdown($project['id']) ?>
```
but I get:
```
PHP Notice:  Undefined variable: project 
```
and 
```
PHP Notice:  Trying to access array offset on value of type null
```

So as a result, the dropdown doesnt show at all

**Comment by aljawaid** [comment]
@creecros I tried this too, but that dont work either.

```php
$this->template->hook->attach('template:task:form:first-column', 'templateManager:task_creation/show', ['project' => $projectId]);
$this->template->hook->attach('template:task:form:first-column', 'templateManager:task_modification/show', ['project_id' => $project['id'],]
```

any tips on how to get it to show up?

**Comment by creecros** [comment]
I will look in the morning.

**Comment by creecros** [comment]
although, its rare that I would choose an override, if I could do a hook, so don't get your hopes up.

**Comment by creecros** [comment]
You have a typo on line 60 in plugin.php

`$this->helper->register('templateTitleHelper', '\Kanboard\Plugin\TemplateManager\Helper\TemplateTitleHelper');`

as for using a hook. that doesn't make sense to me. whats your plan with that?

**Comment by aljawaid** [comment]
> $this->helper->register('templateTitleHelper', '\Kanboard\Plugin\TemplateManager\Helper\TemplateTitleHelper');

Thanks for that! I think I spent too much time staring at the code to miss the `space`... it seems to have fixed it.

> as for using a hook. that doesn't make sense to me. whats your plan with that?

- I'm using a hook for 2 reasons... If a user keeps template title installed, then the original dropdown with not be shown.
- There is no need to adjust the `group_assign` plugin, as that plugin uses an override.
- Using the hook, with css classes, I can reposition the dropdown in the top left of the column. I got this to work and function after fixing the typo you found.  The only thing left is fixing the 2 errors below.

> Long story short, I don't see a way around it, its an override.

- I am nearly there... I am only now getting 2 php errors, but I dont know where to declare the variable and how... and also how to change it for the offset/null issue.
```php
[Fri Feb 24 15:09:45.450265 2023] [php7:notice] [pid 520589] [client 86.152.172.140:64763] PHP Notice:  Undefined variable: project in /var/www/.../public_html/plugins/TemplateManager/Template/task_creation/show.php on line 1
[Fri Feb 24 15:09:45.450342 2023] [php7:notice] [pid 520589] [client 86.xxx:64763] PHP Notice:  Trying to access array offset on value of type null in /var/www/.../public_html/plugins/TemplateManager/Template/task_creation/show.php on line 1
[Fri Feb 24 15:09:45.452221 2023] [php7:notice] [pid 520589] [client 86.xxx:64763] PHP Notice:  Undefined variable: project in /var/www/.../public_html/plugins/TemplateManager/Template/task_modification/show.php on line 1
[Fri Feb 24 15:09:45.452236 2023] [php7:notice] [pid 520589] [client 86.xxx:64763] PHP Notice:  Trying to access array offset on value of type null in /var/www/.../public_html/plugins/TemplateManager/Template/task_modification/show.php on line 1
```

**Comment by creecros** [comment]
yes, but thats your blocking point. you dont have the project variable using a hook.

**Comment by creecros** [comment]
i can however think of a workaround to get you the project variable, i dont like it though. let me dig in and see if there is a better way.

**Comment by creecros** [comment]
nope i lied, workaround doesn't work. and I am coming up with nothing else.

**Comment by aljawaid** [comment]
> yes, but thats your blocking point. you dont have the project variable using a hook.
> 
> And even if you did, now what? you would have 2 instances of the render.
> 
> if you can figure out how to get the project var, then it fixes both errors, btw. the first is telling you dont have it, the second is telling you it can't use what you dont have.

that makes sense... so basically the feature is fully working but because of the variable, it shows an error.  I feel like I am 95% there towards keeping the hook

**Comment by aljawaid** [comment]
can we not ignore the project variable somehow?  as it is not needed for the feature at all

**Comment by creecros** [comment]
its very much needed, but i do actually think i may have solved it. stay tuned.

**Comment by creecros** [comment]
ok, i got it.

**Comment by creecros** [comment]
oh, you can remove the BaseController use

**Comment by creecros** [comment]
noticing some DB issues, due to your schema change. If this is unreleased, then maybe ignore, but anyone using this plugin currently will have issues that will be difficult to resolve. the proper way to alter the scehma is through versions that migrate.

**Comment by aljawaid** [comment]
oh perfect, I just tested it... no errors so far... I will create/edit a task later... but I doubt that will produce any further errors.

Massive thanks for this

**Comment by aljawaid** [comment]
> noticing some DB issues, due to your schema change. If this is unreleased, then maybe ignore, but anyone using this plugin currently will have issues that will be difficult to resolve. the proper way to alter the scehma is through versions that migrate.

- yeh I made the changes before the first release... so nobody should have any issues
